# Generated by Django 5.0.6 on 2024-05-20 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 27, 17, 27, 56, 988131, tzinfo=datetime.timezone.utc)),
        ),
    ]
