# Generated by Django 5.0.6 on 2024-05-21 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_image_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 28, 7, 53, 21, 658880, tzinfo=datetime.timezone.utc)),
        ),
    ]
