# Generated by Django 5.0.6 on 2024-05-22 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_image_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 1, 23, 5, 201122, tzinfo=datetime.timezone.utc)),
        ),
    ]
